language: node_js

node_js: stable

branches:
  only:
  - master

before_install:
- git config --global user.name "[你的Github帐号名]"
- git config --global user.email "[你的Github邮箱]"
- npm install -g hexo-cli

install:
- npm i

script:
- hexo clean
- hexo generate

after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$REPO_TOKEN@github.com:sNaticY/my-profolio.git pages:pages